### ISSUE TITLE
Error while trying get my profile

### ISSUE THREAD

**Issue by mervick** [IonicaBizau/cli-github#24]
When I try to load my profile it terminates with an error:
![error](https://leto1h.storage.yandex.net/rdisk/48bbb6ffbf2f83a5229b397a24acfd9a4d0a8967a661ac05e31f587ed8f6ef25/inf/ObcweaftibETnWUkWpsGri6W4_0cxMsEm5OHfnPfwhEL9H59uOne2awvui4-7MSwUway2PDrJp0Gz17donUTNg==?uid=0&filename=123.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=c72678fc7e35c76ead38cc9d48b74cba&force_default=no&ycrid=na-7a107053e75be3794aa31f74ce4bd55a-downloader4g)
If I open other people's profiles - everything is ok.

**Comment by IonicaBizau** [comment]
Thanks for the report! :sparkle: 

This seems to be a bug in `pngjs`: https://github.com/niegowski/node-pngjs/issues/3

`pngjs` is used in [`image-to-ascii`](https://github.com/IonicaBizau/image-to-ascii). I have a [work-in-progress branch](https://github.com/IonicaBizau/image-to-ascii/tree/lwip) to remove the `gm` and `pngjs` dependencies and use `lwip` instead–that will not require any binaries to be installed (currently we need `graphicsmagick`). This will be fixed in the next major release of `image-to-ascii`.

Like always, contributions are welcome! :sparkles:

**Comment by IonicaBizau** [comment]
@mervick I recently released [`image-to-ascii@3.0.0`](https://github.com/IonicaBizau/image-to-ascii/releases/tag/3.0.0). By upgrading to that version this issue is supposed to be fixed. :sweat_smile:

**Comment by mervick** [comment]
Thank you so much!!!
